"""upgrade_users3

Revision ID: 0483335f8040
Revises: 08d84b2a1a3b
Create Date: 2024-03-26 20:00:22.560915

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0483335f8040"
down_revision: Union[str, None] = "08d84b2a1a3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "subscription_plan", existing_type=sa.BOOLEAN(), type_=sa.String(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "subscription_plan", existing_type=sa.String(), type_=sa.BOOLEAN(), existing_nullable=False)
    # ### end Alembic commands ###
