"""upgrade_users2

Revision ID: 08d84b2a1a3b
Revises: a1e4608a9aa2
Create Date: 2024-03-26 19:58:03.800141

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08d84b2a1a3b"
down_revision: Union[str, None] = "a1e4608a9aa2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_verified")
    # ### end Alembic commands ###
