"""keywords

Revision ID: aedb480e325e
Revises: 6999c503427c
Create Date: 2024-03-27 22:28:23.527279

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aedb480e325e"
down_revision: Union[str, None] = "6999c503427c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("keywords", sa.Column("project_id", sa.Integer(), nullable=False))
    op.drop_constraint("keywords_community_id_fkey", "keywords", type_="foreignkey")
    op.create_foreign_key(None, "keywords", "project", ["project_id"], ["id"])
    op.drop_column("keywords", "community_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("keywords", sa.Column("community_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "keywords", type_="foreignkey")
    op.create_foreign_key("keywords_community_id_fkey", "keywords", "community", ["community_id"], ["id"])
    op.drop_column("keywords", "project_id")
    # ### end Alembic commands ###
